services:
  - type: web
    name: portfolio-backend
    env: docker
    rootDirectory: backend
    envVars:
      - key: APP_NAME
        value: Portfolio
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: portfolio
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: ""
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: your_gmail
      - key: MAIL_PASSWORD
        value: your_gmail_app_password
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: your_gmail
      - key: MAIL_FROM_NAME
        value: Portfolio 