services:
  - type: web
    name: portfolio-backend
    runtime: php
    buildCommand: cd backend && composer install && php artisan migrate --force && php artisan key:generate --force
    startCommand: cd backend && php artisan serve --host=0.0.0.0 --port=$PORT
    envVars:
      - key: APP_NAME
        value: Portfolio
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: localhost
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: portfolio
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: "" 